/*

VR5 pano viewer 1.0.0
Copyright (c) 2009-2010 Ninoslav Adzibaba http://www.vrhabitat.com/


Parts of code for setting panorama and rotating by touch are based on 
iphone script by wayne a. lee http://www.bunnyhero.org/ and (c) 2008-2010 wayne a. lee (The MIT License)

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/




























































































































































eval((function(x){var d="";var p=0;while(p<x.length){if(x.charAt(p)!="`")d+=x.charAt(p++);else{var l=x.charCodeAt(p+3)-28;if(l>4)d+=d.substr(d.length-x.charCodeAt(p+1)*96-x.charCodeAt(p+2)+3104-l,l);else d+="`";p+=4}}return d})("var _1=\"iVBORw0KGgoAAAANSUhEUgAAANAAAADwCAYAAABxCOpCAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAARoJJREFUeNrsXQlcV8X2P2yKCwi4guKCu6CmuJuKycs0l6ywp1avFZ/50tRS61+Z9eqpqZU+K7V62WKlrba4Ji6ZooILiooCIgKCyqrs8Pufc+/M7zdc729VkmWOn5H7u8vM3HvPd84yZ851MhgMIEmSJMfIWT4CSZIkgCRJkgCSJEkCSJIkCSBJkiRJAEmSJAEkSZIEkCR` 9\"EmSAJIkSQJIkiQJ` g!IAkSaq95Fr9uhyh3eHEBgJeXIRjZVjKTWW4DD2XVNsBdANw6B7qYKnLihvbT6ApwVKIpUjdjiiVQJIkAaSCx4WBpR4WD4BugwG870EstTWdVnweIGszQOwf+OMalgIGqjK7GnNyEn9Se95sO8tg2FnEniOBtyFA2y4ALcZiPzpgF73U04pSsC+ZWK6qAHbC9p0M6nbuWYCE0wzkRQLgi7GUcinq5HTXLQU99tuJPT8q7gDNm2Jz+LccByODi1oco9TUDLeoqDMe6elXXX18Gl3v2bNLZvv27fIA0jPY/dE7KKV7wn6wq4ZXT0asfgvqIrjtRlKnAYBve4B24ci/ncxfU3AM4OT7AHnp+OO6+gKHlzsIID0mRMaDRgDdRwE0mcIAbieV5iBuEPCZBwEunkA+y2Z95YAiIJXdKiBh313VfvvgYNB1Jj7OfpX/7koOAPyxiA1kxXgvZRJAtwdAbip4PHwBer6CP1udPHnSfcWKFb5r1qxpxc8MDw+/+MYbbyQ3a9YMR/KiOIA//427URJAPr680lswgrswiYTgCUKp03QSHVu8eHGLlStX+qekpBCwoH///tn+/v6FAQEBBdp68NyL+i0UXwBI+wml01H8kUd9ZkAqtSSRbH+fEXVVyT3oeRx8BpVklFS6NuLWzA37Xowawb6VbGAQ3oEE0F8FICc24uPIOQBffr0+u3fvbjh27NjueXl5NzBBy5YtC7du3RoTGBiILyx3K0DUJ6R6ETPezGiOAHI2SZ72gwBaz6T9Dz30UMcNGza0sLc+6ueUKVPS+vXrd+2BBx7INh0pQoBd3QZwZh/+yGGjdxFTgcodA5DyDHEAgsYAQ1fgOOB9wP9A36KUIvfKemv1u9a/1vdk3yMoRBMB9sxkKnW1B1B1dGMztamFH46cgbQDGa+rHniISAo8+eSTHdVf7t1VO0VR/5xvAjxOzO5B6dOgOfZlIu2fN29eK0fAw/u5ZMmSdg8++GB3VBmHUF0ZGRnYRl2UqH5PoKR4DcC/j8r0JDnAndQw1hdH3js+Q+/mBB6SPpUJHp33J50Itxn0+PKbBOFmvbVr1zbhqpI5ioyM9CIpNWzYMARd+x4A8buZSnQzfWAqUCAydx1fqp8AcKtukuqiIqih/gAd5qGxHwlw+FMmRWkUL0IQ6Uoj64NQkw70I3tvdkN+IOA/AWc9Bnhcu+XqWxM3Jm3KTtnrxJEAuvWEtoebMtKfO3fOppHzt99+80IAIWN4dCVMMfvFbjuoovRpH4wS6A4uBSvjRsmmo7Jo0aKzKJUuYf8HAAxui/bRRrSPDnK1jkCkevXAYNvzIylc15d+FJ4rND5DnzE+2Q0CGxRWzmsrjUH7Zw177gYJoNuvytlMx44d81C36rZh0sOFwOCAHcQ9gFhf01FcdbMmBW+W5s+f33HdunW+H3zwwVkcCHDwaPMsml87AY58yR0joM51ldkwz8UAVK81/cg7kqc8m7ot6xaq4CnBus7+hoMU1utS4KimqxZn7JMLljKUmIkJoiNEAui2UtEV+r9Dhw42jZYXLlxgDO7qzYx/N+YJshlAFaVPQG/804nsFGRq/7/ijk+dOtUwJCSk19y5cxNV753XXQD9mwGc+BDg+iWm0hVbBlGEkwlArj7Kk0xS7Z+6reqyZ1mKwEknKX2JOS0MNwEiHglSCqY5uHKoIRKoOjoRDOpLyEqiH4MGDbpmK/OpRnkdZLjGzcEUseCAA4McEc1G0o5ly5a1MOfAqCwi22jAgAHd1fupj7Zgj9moSra00UEiAKiOogZfj72u2EANejZgz5Jc6HAZCw1SV5mEc6SQnUYexVxQ57SKa5L0qa4AYqNZWipuFpN72sPDwyZb5qeffmKRAU27cDXOMeeBfyeUPopn76+SPnqOkd69e/ei+S8UqAEIopkIAT9Q3dMIjggXy04Y8mI6171+8rp7WV6ZMgB4BHvkqafkJzHpXLLb2bnMnsIkjFjKBYlT40Koqms0dqmqSxddYFIo25aLDh8+zOyg+h1EO8gO9Y2kT32AJgNpJKcJ079a+ohEdtfIkSO7CyB6DlQ3d31V1YxwNg8gL8VjmPtnrtED5znIk0mg7ESmbpWDpBqpwpWqI2TBedrRs2fPPFsu3Lt3L5NAivFcjwHCyY5nxcKH6ilhQz/88ENTWy4kCXnixIlDBoNhL5Vvv/02huwYKhSlcGtB1P9ZUCZ3FTvPhdk8OgCqrzoQolQHgouHS6nqQCjHgelSqgRQzZZAZaoEyjtDP0aPHm0TE1a0gwKCmBRytuNZ4fkBPclfRfWQGmXLhdOmTUtWIyFUokgDcgJQOXDgQAyBisDUtWvXa46CKCwsrCuzibrjkHK/6iXUtfO4C7ulYv8cY/ZPN6P9cwlMsXcyar2GAsigGqQJsWQH0fyOrXYQGf1MLnRmALKqggnqG0ot774V67FOjz766BV16/QmNZjywv/Qxt6BZR8K0jQ6QmCKjY09QtLJESDR4IDtsIgLr7+hndeGSVlBCkVwL2Id5o2EoovMA9fG6IG7yo19tGkkgGoogPhan3xywtKOSZMmXbLlQtN8kHs7rsbZYAdx9Q1Ha/e2tOPnn3+2SX2bOHHiJVX6EFDS9mK3TwHEb8WeIIiOfQSw/w2A8x8A5BzGY7kknQhIJJHsfShbt25tQpEZFKEB0O4hJoXqCGoqWz/VCMHj2kgM4fHoxR0IBclSfasdEogkTgEavIdpR58+fWyyg/7880+mdrn747jrCba5s11Um6Jdd1L/yN6gEd9GAF1mhvl+/I+kDa2JucL+0u+LAIkRANGrAA69oQJJlUi7du06QkGm9jyYhQsXsnCiBqhq+nfWeBuZJG0aoPRICOExhe/knWcSqEzCo+YCSLCDrihq3NNPP33FFjWOvGbfffcdgsgZR+Y2PcGKO1vjfRtC+z777LMmtnSQmF+NrC5FcCfQoj6aC6EocFoLU6QOAMpSBZozScdDKHWi31clUlE6qabR0dFH7FHpyB4i76AKluYjmEfOTZhAxe0GbZRncSjPCCCvYV6sjaR4EOZqhpWXO7HirCnKfgmg6g0gHCmvpKJ6RGqHze7sbdu2sRWlHt2YGmcpqpkZ3e7eXH378ssvfW1ph5YnqFsEjKJM1XNoUo0ojIgWlTGVicCUo0qmxD0AR99GvJ2mtUyk0tkDIgr5UbfqtlO9hord42y6lzrKAFB4vpDuXVlqwBwI6awvysUIkPqq2qp49byF4sX2NaRzsNC5rgQsqGHR1jUZQMyRQIxXcIZ5ty7bcqHJne3ODW1dd3bFRXOteyEfepD0sjXubc6cOcwuu7KXSZ8SvahpAUjFql1HM/j5qEodfA8xFUXnoDoXY6s6R+olRYcjUJoDtA8CU3QCB5Cf4oGLYR647twDV5gOxjg/ZT6JgNgK8dIVoO2dKLGH4l+Uwu3uVPcBefKas3MbgXESVwFsrQCSazXvf5k6qqccxHc4evz48dnh4eE2MRi5fHF0J3d2IKpXGWBKRFKBt8E49+MzqKL0skwjR468wlbCpmD9x5j0sWhXsBwBTDXlM/fRnwD0bYh1dX7vvffO0nohW9oXos/JDvqTgYflbiBgIURP5Tes6EC4lqVKmIBOCJAuarRFndb6LZAwpmXoJXh/BecQ88cBLpxjA4Bx0R/UcHd4dc8LV66+qKupxKjEsMS4tlyocWe7m7GDmPetCS3eUxjpq6++ssl9bZKG146BKQ7MqmdLI42uqQ6HmM+QUfPInrJ14vX8+fP11C23pkzCuqp/27RXHAi7TQ4E9w7uTLKVo2Qe+E88ZzoKlBEcPOSto/PFoi4Bd0WpUw/VYJ9xKOlexmtfBOg+Hi+hNj0F6V5j8w9WdwkkeOOun6LJQYpKIHeutQsFd3YAAxC5s4v58oaKcz9+A8npQC5iW0J3yJlBTg1ybgCk7mejcok9SydYwg0GokKUkLknUMoOfPLJJ9NsmcBNSkri0eeN2XtmAPJQ7Li8A4IDYQh3ILTqqah2J6+7p3+e3iRnd453bmSu2baU5Q9BDa55hXhltXi8xRW3Zu44GFEZ1B9NuZ8BzkWDGkhaUFOlkXPNAZA\";var _2=\"iVBORw0KGgoAAAANSUhEUgAAAFAAAABBCAYAAABGmyOTAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAEeRpVFh0WE1MOmNvbS5h` J\"54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+Cjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDQuMi4yLWMwNjMgNTMuMzUyNjI0LCAyMDA4LzA3LzMwLTE4OjEyOjE4ICAgICAgICAiPgogPHJkZjpSREY`!K%cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uI`!*\"hYm91dD0iIgo`!K!`\"g%G1w`!0(bnMu`\"y#uY29tL3hhcC8xLjAv` L,ZGM9Imh0dHA6Ly9wdXJs`!n\"9kYy9lbGVtZW50cy8xLjE` O-eG1wTU0` X(ucy`%K%jb20veGFwLzEuMC9tbS8iCiAgICB4bWxuczpzdEV2dD0iaHR0cDovL25zLm`$Z\"L`&?!94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQj`!L,dGlmZj` [90aWZm`!V\"`!G-leGl`$g)`#G-2V4aWY`!R\"yIK`%_!HhtbG5zOnBob3Rvc2hvc`!~:waG90b3Nob3`\"=#` e#eG1wOkNyZWF0b3JUb29sPSJ`)X$Q` M'gQ1M0IFdpbmRvd3M`\"&\"HhtcDpDcmVhdGVEYXRlPSIyMDEwLTA1LTE5VDE1OjI0OjQ0KzAyOjAw`#B\"B4bXA6TWV0YWRhdGF` E7MwOjQ3` J29kaWZ5RGF0ZT0iMjAxMC0wNS0xOVQxNTozMDo0NyswMjowMC`\"V\"ZGM6Zm9ybWF0PSJhcHBsaWNhdGlvbi92bmQ`$#%cGhvdG9zaG9`!1'BNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkVFN0U0NjUxOUQ2MkRGMTE4QzNCQzQ4RjAwQTI3QTNB` e+Eb2N1bWVudE` j&ZG` o!E` =SPcmlnaW5hbERvY3`).\"SUQ9InhtcC5kaWQ6RUQ3RTQ2NTE5RDYyREYxMThDM0JDNDhGMDBBMjdBM0E`%9#RpZmY6T3JpZ`+g!Rpb249Ij` 2*WF`(g!sd` 7%cyMDAwMC8x` \"\"`$.\"`(j\"pZUmVzb2x1`$'!j0iNzIwMDAwLzE` #!`\"5#`(w!Ol` p(5Vbml0PSIy` 7)k5hdGl2ZURpZ2VzdD0iMjU2LDI1NywyNTgsMjU5LDI2MiwyNzQsMjc3LDI4NCw1MzAsNTMxLDI4MiwyODMsMjk2LDMwMSwzMTgsMzE5LDUyOSw1MzIsMzA2LDI3MCwyNzEsMjcyLDMwN` K!UsMzM0MzI7OTY4NTc1NDFDNzgxMzBFQUE5NTgwRUIxRDNFRUVCNjk`#N\"G`*o!6UGl4ZWxYRGltZW5zaW9uPSIxMjg`\"x$`+[!OlBpeGVsWURpbWVuc2`#N\"MTAyN`($$XhpZjpDb2xvclNwYWNlPSIx` [)`#00zY4NjQsNDA5NjAs` \"\"EsMzcxMjEs` \"\"I` 1#I` 9#MsMzc1MT` H$Qs` b\"cs` \"\"g`\"u#Q`\"}#csMzQ4NTAs` \"\"I` )#U` )#YsMzczN` C!czNzg` )#k` #!ODA` +!OD`!K!zODI` )#`!C!zODQ` )#U` )#` j\"OTYsNDE0ODMs` \"\"Q` )#` 0$c` )#g` \"\"TI` *\"T` I#TUsNDE3Mj` ;!3Mjk` \"\"zAsNDE5OD` ;!5` i#5` i#5` i#5OD` K!5O`##!E5OTE` )#`!#!5`!!#5OT`!S!5`!)#5`!r\"IwMTYsMCwyLDQsNSw2LDcsOCw5LDEwLDExLDEyLDEzLDE0LDE1LDE2LDE3LDE4LDIwLDIyLDIzLDI0LDI1LDI`'K!LDI4LDMwO0E0NjM4RjQ3Q0JBN0VEOTE0M0JCREQ0QTY4RTk3QUEz`&!#`1<(6Q29sb3JNb2`/o!` /1SUNDUHJvZmlsZT0ic1JHQiBJRUM2MTk2Ni0yLjEiP`42\"8eG1wTU06SGlzdG9yeT4`3.\"DxyZGY6U2Vx` E#` +%bGk` >\"CAgc3RFdnQ6YWN0`(j\"Jj`25#k`!Z\"`4[!zdEV2dDpp`/a7`.YK` k)3aGVu`2~F` O)zb2Z0d2FyZUFnZW50`4HDLz`#%#CA8cmRmOmxp`+k!CAgIHN0RXZ0OmFj`.l$c2F2ZWQ`,.\"` 7)luc3RhbmNl`0u'p`0z\"U`0RJ` l(ndoZW49IjIwMTAtMDUtMTlUMTU6MzA6NDcrMDI6MDA` I/NvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDUzQgV2luZG93cy`-Z\"`%O)2hhbmdlZD0iLyIv`&($PC9`&4,8L3htcE1NOkhpc3Rvcnk+Ci` B&RGVzY3Jp\";var rotY=0` #$X` $#activeTouchId` -#lastX` 9!lastY` %!scalesum=50` ?\"e` -!last=1` ,!first` d!=false` +&Sound` *'directional` +,soundSourcePan=12`!'\"` b!Rotate` l-lide=tru` .\"gor` B!` &#Left` 3&limit1y` \"&2y` \"&3` &\"startx`!G\"tart` 0\"doLog` Y'` ;\"` ^\"` G\"` ^\"` &\"hasContent` '$Description` .!vi` \"-infoT` Z\"` &!`!3\"` &!` M\"erticalArea` ,!toolBarWidth`$f\"utoO` g\"appMod`\"P\"autoDeley=auto`#@\"Delay*10`$f#`#.\"Timer`%=%timer_is_on`#m#window.onload=fun`$`! initialLoad(){document.bgColor=bgd` $!;if(vrTitle==null){` '$\"\";}` 9!Sub` 2+` )%` ;%`#-'` =&` )(` C#`$Y!Zoom` >$` '&0` 7&Tilt` 4)` ,!` 6'Pa` ~%` '%` U'` (3updateOrientation();checkA`$3\"();if(!`$@#`#*(ody.setAttribute(\"class\",\"` F#\");}else` /A\");}` ?%t`#D!`#n#`$f$scrollTo(0,1);setView`#3&,`\"l%,-`\"9$`!w!`$1&.length>0||`#|)` /%){set`(*#`%;$,` V&,` I));`!g%getElementById(\"info\").remove`\"<-);`)-&`*M\"`#!\"` +'`'A\"`%v-`!^'`)]*`+3#`)_)` l+` .(`,3#` A*`!*&navigator.onLine){addStats(`$k$enable`-I(}if(` 0\"AutoButton&&` ='){`*\\(`-m!` g! ` F/||` ?665`!=#` ))`'d\"!` Y,){`,s!ideauto=`$95auto_holder\");` H$.parentNode`$f#Child(` 8$);`,d\"`#_(` +#`\"k&`!M#`\"$#`!G$snd`!46`0x!`!A*snd`!28snd)`-[\"`&N\"udi`\"91sByTagName(\"audio\")[0];` K'` n4` 8'`%=$`0h\"stenTo` bL` K).l`.n!`#*!`/q&OnStart){`/g*setTimeout`$Q\"Rot()\",`0T%`+=(`#I,controls`#S%`)J6showVR(`+e!TouchArea();`-k\"Ic`-e!};`0t%`-v/`\"|!c`*-\"Type=\"show_\";` )'+=get`.Q*`!e5page_wrapp`!v!`-t1` p')`-a5`!w5clearOfllineInfo();postaviPoruku();}`\"I%`!i,{switch(`3v$` 2&){case 0:return\"vert\";break;case-9` 2%hor` .( 9` L%` *,18` [1default:;}`!`&`$d$`$+\"trlarea`)%6toucharea\"`0\\!`-E&platform!=\"iPad\"){` e$`(>4` 8$`)W\"info` }:`0T\";` A$` _4` 8$` q\"`'N$` ]:`'k-`&b!` P$`!h5` 9');`#j\";}`\"N%addEventL`**!er`#6#`3|!\"`4,#ouch,`-K!);` 9<move\",move` *Iend\",end` (Icancel\",` \"\"` 3Dgesture`\";#onG` *\"`,F!` 5Fchange` U'C` ,!,tru` ;A`\"L!` T%End` S#`%5%`#iL` 9<`$\"3` 7<`$$1` 5<`#~7` @7`#u@` =>`#{:` >>`$!4`3'!oadingE`)J6` ;#\");` D$`)@4` 8$`047cubes`004\"visible\"`/F(setView(`#?!Zoom`%c\"Pan`%k#ilt){scalesum=` >%*500;`4@\"By`$K!(0,0,5*` M%` $$Pan`\"f\"es`,/8ube`,=%esa.style.webkitPerspective=`!C$`!v*C`2^\"(vrTitle,vrSub` #$Descrip`1Q\"`/i6itle\").innerHTML=` f#`#U6sub` B0`!3$;if(`!1).length>0`!,7d` E&` h+` ^';}else`27!descTxt`#@6` d);` H#`&,4` 8#);}`1u$` e#`1_=` H$Height=` P'.offset` 3\"` C!window` C#getW` %'(`3|!getOrientation()==\"hor\"){if(appMode){verticalArea=1024-`!7&+10`3N!`!<$`&)\"top=` J(+\"px\"`#E$` ]-(768-`!`()` IT` o/` l(` k(2` KH`'z%`#4-`%W!`#[)0;if(typeof` 2#`&7#` 9\"=\"number\"){` J)` 9.`#)#if(`%K%`%U$`!o#&&` \"4.clien`%E#` {+` /A`!*/body`!''body` bA` 8-;}}}return`#-)`+_'`#^%Width`#Y)` -!`#L5` 8\"`#S-` 1\"` 8-`\"_` c!` y*` .@`#2I` h8` 7,`#K-` /#`/9(`0b!Area(){limit1y=65`*R9` A\"x`)j\"toolBa`#6)` 8$768` 0+if(enableAutoButton&&` ,\"Sound` s%S=` \"#+55;` $#M` ,$`!!\" ` X1!` 3W` U#`!3E` Z-+55`\"U*` 16;}` $!2x`'8\"`#S5`.w?` c\"y`,p)` /\"3x=924`&5&has`4M#==true`\",#2y`,z*20`!z(2y`!\".-10`!z#3x=668` %$y`\"9\"2y-7`%~!has`36'&&!vi` #*`\"E/vert`\"R#slideTop`!,10`\"P%` ?$+2` -#`!:*`'|#`'l'check`'o&` %!X,` \"!Y){infoT=false;`&;%`%>!&&` E\">`$w$` *#Y<`(S#`3&!!first`%m#prikaziPoruku(\"Please wait...\")`'~1` `\"autoOn){togg` 8\"Set();` 2\"`$[!;}}playPause();`*D#`!t\"`()7`!w*M` )$`!~#`\"\"0`!:&();`\":%Rotate){` \"'`!P#`!42`!,(3x` ~$` )#y`!(*2y&&useLogo`\"j!`\"HXopenIVRpag`\"l6`!P(2`!M+2y`%N#x=` A\";` )!y` (\"Y` (\"`!'\"` k.{` ,#`!E#`.Q&tar`.W\"(e`%l'` -!`#L#` '!` r\"` 2&` *\"`\"]1`/%ge`0$ById(\"auto_btn\").removeAttribute(\"class\");` 9@set` I-,\"on`';)`'r#` W5sound` uU` R(`!38}`#[!x=e.targ`2@#es[0]`2z#X;` =!y` (6Y;clearOfllineInf`'v#timer_is_on){` \"'`+,#` P!Timeout(r`(1!TimerId)` 6\"Interval(go` 9\"`#8\"auto`(_\"OnIdle){` 6P`!D(`&l\"` L(=set` i$`$t!Rot()\",autoDeley`!E\"`-Q+`#E\",`#*\")){e.preventDefaul`),!ctive` N!Id=e.changed`#I'identifier;lastX` 01pageX` ;!Y` '5Y`'g2`*EF`)Q\"`!r/`0@$`)[&mo`\".#(e`\"B1if(`\"M)){for(var i=0;i<`!t,.length;i++`,p\"`\"4,i`\"}(==` n+var t`\"g.i]`&r!`\"x\"`-w$-10){`%7\"By`!~\"`#s!,`#Y!,` H\"X,` O#)`$.#` 0#`#|#` 6#;}break;}}`\"p'en`!:\"`\"c3var lastInfo`$p8` <(`$x8`#O!nfo`*f#=`*h5info\"`$5!`.r!&&hasDescription`#?\"razX=Math.abs` C\"x-`!f%`!x\"razY=`/c\"` 2%`&W!razX<50&&razY<0&&vi` p.slideTop=getWindowHeight()-100`0N!`!p#.style.top=` M$+\"px\";`$b#` ,&20;` }*`+k#`3:#=`%2$75`0J\"Slide` =#`*M(updateIcon()\",300)`2^&`\"0)>0&&!`\".,`!e2verticalArea`!q*` -)`!q.`)P!`!^@`!j(`!f&` `*&&` M&){prikaziPoruku(\"` 1! d` D& DOWN to hide it\")`!*(`+(\"`! $`\"X+` ZKUP to show` p3`3:!`1;*`+%#>0){`,3\" `\"b\"`)9'cancel`)>%`.W*0;` ?&`*N6curX,curY`'1\"e`(_6cubes`(t\"!e`!L$;}rotY-=(curX`(B!X)*0.2;rotX+` 2!Y` 2!Y` 1\"if(useLimits`-=!rotY<=left` 0!||rotY>=righ` ''X<=Bottom` ('>=Top` +!`#p-PANO ` 6!\")`!\\\"`*G\"max(`!\"%,` -\"in(`!#&,rotY))`!y!` I&`!0'` K&`!5$,rotX)`!!\"` I'-90` B&90` >$setCurView(scalesum` 6!`!3\"`$G'` +:`0W!`2^!Sound&&dire` T!al` +#soundSourcePan>-361` %,<` /!!(`% /sByTagName(\"audio\")`.f\"used||` (Fstopped)`-O#oundAngle`#$\"round(`.`%`\"7!-` *!floor` ++/360)*360)*` ,!/` 1*`/1\"myAudio`'40`!M2;if(`\"i+0){` $*=360+` %*;}` P$`\"+!` K%`\"8\"` G%` *!;}`0l!el`\"P'abs`!(+-` G&`)!!` H$>18`*_!` W#360-` %$` s\"` S!Volume=1`#9\"`#S\"` ?$/18)/10;` =(` J'.toFixed(1)` 6)`'7%`'M%` 3',0),` A+` 3'+\"\";`$##.v` --`!q\"k`+J>k`0{#webkitTransform=\"translateZ(\"+`(9$+\"px)`-%#X(\"+`+!\"deg` -$Y` /\"Y` /\"\"`)$'onGestureStart(e`(}!timer_is_on){` \"'`1J#clear`3M$` {\"TimerId)` 6\"Interval(go` 9\")`%p!autoR` +!OnIdle){` 6P`!D(`0_!` K)=set` i$\"`!*#()\",autoDeley`!E\"check`00!Area`0-()){e.preventDefault(`&q!`+q\"AutoButton`#%!!autoOn){togg` 8\"Set();` 2\"`2=$`3I!` d0`0e$`#~/Change(e`!;1`1n!sa`%k:holder`1t\"`%c$>299&&` &$<701){` &$=(1-(1-e.` ,!)/20)*` 4$` X(<300||` i%700`18-ZOOM`1?&` x%`-,,max(30`0F'700,` F$)));esa`'})Perspective=`!R%`#*0End`#6!` @!last=`\"0#;`#;/`13'tubOu`(#!` +9playPause(){first`18!`%)\"`.7Rvar` q!Btn`$\\6`+F!_btn`$o\"`+a$`1V$` ($`14${` j#.removeAttribute(\"class\");` 9$set` --,\"off\");`'7\"` +\\n\");}do`##!`#>)` +%`3$!`1QQ`\"G=` 8%lay();`&~+`!;! ON`\"C%` c)` 84PAUSED\")`&S(`*\\&(){`,,`-w#`-B#On`,iR`,k%`!e#`-NQ`,09`!{/` B!`$;!auto`&f9auto`&x&`(7!`.C!`-j!`\"Q$` ++`#Q+A`#0%`$.#`!.#`&B6` 9$`'&= `!>#Btn!=null`!;-if(!` +!`!<\"`!A8`%8&`(<\"`!l6FF`%c!`!H\\`(_!}`0L$`-+&penIVRpage(`!|!navigator.onLine&&!appMode&&linkLogo`$i\"r=confirm(urlC` %\"`$T!r=`%J!){window.location=\"http://\"+` b$URL+\"/\";`2@\" if(useOfflineInfo){showOfl` )$(`(G)`4&!A`!Y\"`!y\"`!,#`!|&standalone){`\"\"#`'&#`#t!` +$`(z\"`\"n.`(\"!`!3){`'%6aa\").innerHTML=\"\"`02(`!x,`#?!nowWidth=getW`!v!` *!`4?#nowHeight` 5&` *\"` 9#winw` Y!` _$+2` 0$h` R\"` Y%` 3#imgX`3>(` Q$/2)-104` <$Y` 5+` ^\"` @!20;`\"7F<div `3!='top:0px;left` $!`!v!:\"+`!~$+\"px;`!r\"` 0\"` &\"` 2!backg`!J!-color: rgba(0,0,0,0.7);'><img`!!(\"+imgY` Z!`!/!` +!X` +!'  src='../vr_files/styling/o`&X\".png'></div>`$\\(`)c#Icon(topPos,leftPos){`%x\"\"`!7.` C\"`!?(` M#`!-=logo-ipad`!J\"`!>(update`!D!`'v!use`)S&` y#=limit3x+10;if(getOrient`)K!()==\"hor\"` M\"`!_\"` K#y+5`$n6bbb`${)`\"Y7`) #` m/1` 9d`*e'addStats`(w#currentTime=new Date`'^!month=` 4'.getMonth()+1` >!date` 2,Date`)4#year` /,FullYear` <#minutes` v-` 1\"` >#hour` 2-Hours();`!a\"`!h!+\"\";`!N!date+\"\";` v$` #+\"\";` f\"` m!+\"\";if(` V!.length==1){` l\"\"0\"+` %!;}if(date` 8(`!\"!\"0\"+date` =!` }#` \\)`!8#` f!` &\"` F!`!9!` =(`!O\"\"0\"+` %!;}var javi=\"vr5\"`\"^#stUrl=`0A+.host+` %,pathnam`$c\"sta` U!unescape(\"%68%74%74%70%3A%2F%2F%77%77%77%2E%76%72%68%61%62%69%74%61%74%2E%63%6F%6D` Q!3` 1&73` W!0` {!0%3` n\"3%3D\")+encodeURIComponent(`\"-#)+\"&d=`#h#+\"-`#P\"` $!year+\"&t=`\"t#` 0!`$f%&s=\"+javi+\"&dev=2`#%\"el=`(M%create`(R#(\"iframe\");el.setAttribute(\"id\",\"statifrm\")`(~6ccc\").appendChild(el` j\"tyle.visibility=\"hidden\"` {.src\",`$1#);`3@-autoRot(){timer_is_on`4,\"`3g!Interval(gorotate);if(enableAutoButton){togg` ,\"Set();autoOn`4`$` U$=set` i%\"play`!7!\",10`!I/` 7%{if(`!T'){scalesum`2l(` ,$*100)/100;rot`3Q)rotX` 1)`3K)rotY` 4&`/:#imits`!;!rotY<=left` 0!+2){goLeft`\"<$else ` B#>=righ` D\"-` @&`#R!}}if(!` ,\"){rotY+=0.05`.t#rotY-` *#` h\"X>0.1` E!X-=0.1` ~)X<-` 5%+` 4&` +!=0` ^!`\"q$>501`#1&-=` ^'` -$<499` 9&+` ;$`#f&500;}setCurView` P%,rotX,rotY`.\"\"esa`(/&`'F-ubeholder\");esa`'H#webkitPerspective=` v$`\",$`%Z#`%W'`1C\"Poruku(Tekst`$H!showNotifi`,@\"s`1;\"`!99ddd`!H#`2?&` m!`!X'opac`)*!0.8\";se`0>!out(\"sakrij`!B#)\",1200)`!R5Duze`!g$` W~`!L)30`!T!`!O%` 2*`!\"H`!*,\"`)o(ostav`$1$` NEvar por`)i)getW`1/!Width()/2)-170` D$`)w)` C%Height` G\"60`!d'left=porX+\"px\"` .'top=porY` 2\"`2r!cacheStatusValues=[];` $-[0]=\"un` 3!d\"` -/1]=\"idle` (02]=\"checking` ,03]=\"download` ,34]=\"updateready` /05]=\"obsolete`1r\"` ?!=`4e#appl`(B#Cache` \\\".addEventListener(\"`\"=#,log` 5!,`-6!)` 66`\"2$` )E`\"@(` ,Eerror` %Fno`#)\"` (F`#3%` )Eprogress` (F`$W(` D-`(o%` 1$(e`(n\"online,s`%)!,type,message;` 5\"=navigator.onLine?\"yes\":\"no\";` Q\"=`%_.`!_\"` 9\"];type=e.type;` w#=\"` y\": \"+` $\"` 2$+=\", event: \"+` H(` 5!` n\": \"+` $\";if(` {!=`$`#&&`!b,){` W& (prolly a syntax ` Q! in manifest)\";stopLog()`2[!consoleLog){` %#.log(` o#` ?\"`\"d#`)c#){` Y&if(informWhenOfflineAvailable&&`!v$`(5#||` )#`&=%)&&!appMode){`/t.\"Panorama is a` p$ o`!#\". <br/>Add Bookmark (+ sign)` 1%to Home Screen\");}}}`*$3`&9<`&A$(){` J4swap` %!();`#C(\"swap`+S\" has been called\");}`'C$doLog=setInterval(`!)'`&R\"`!L\"();},10`1j!if(!`%E.`$|'`2%&` ,${clear` |%`!2!`0{\"`,x@remove`,rI` =2`-#;` @1`-\"?` C1`-+9` =1`-+<` @1`-.<` @1`-1<` @1`-79`'Z%`'A-`*2#\",stacemo`-u-` 1#`-}$provera=e.data;if(` *$=\"opaopa\"` C\"skidaj=document.getElementById(\"cubes\");` B\".parentNod`\"7$Child(` 8\");alert(\"Licence for this domain is missing. Please visit vrhabitat.com\");`\"a#lo`'A\"=unescape(\"%68%74%74%70%3A%2F%2F%77%77%77%2E%76%72%68%61%62%69%74%61%74%2E%63%6F%6D%2F%0A%09%09%09\"`(b\"metas`\"Y0sByTagName(\"head\")[0];` J!`\"\\4` 8!);}}"))