/*

VR5 pano viewer 1.0.0
Copyright (c) 2009-2010 Ninoslav Adzibaba http://www.vrhabitat.com/


Parts of code for setting panorama and rotating by touch are based on 
iphone script by wayne a. lee http://www.bunnyhero.org/ and (c) 2008-2010 wayne a. lee (The MIT License)

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/




























































































































































eval((function(x){var d="";var p=0;while(p<x.length){if(x.charAt(p)!="`")d+=x.charAt(p++);else{var l=x.charCodeAt(p+3)-28;if(l>4)d+=d.substr(d.length-x.charCodeAt(p+1)*96-x.charCodeAt(p+2)+3104-l,l);else d+="`";p+=4}}return d})("var _1=\"iVBORw0KGgoAAAANSUhEUgAAANAAAADwCAYAAABxCOpCAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAARoJJREFUeNrsXQlcV8X2P2yKCwi4guKCu6CmuJuKycs0l6ywp1avFZ/50tRS61+Z9eqpqZU+K7V62WKlrba4Ji6ZooILiooCIgKCyqrs8Pufc+/M7zdc729VkmWOn5H7u8vM3HvPd84yZ851MhgMIEmSJMfIWT4CSZIkgCRJkgCSJEkCSJIkCSBJkiRJAEmSJAEkSZIEkCR` 9\"EmSAJIkSQJIkiQJ` g!IAkSaq95Fr9uhyh3eHEBgJeXIRjZVjKTWW4DD2XVNsBdANw6B7qYKnLihvbT6ApwVKIpUjdjiiVQJIkAaSCx4WBpR4WD4BugwG870EstTWdVnweIGszQOwf+OMalgIGqjK7GnNyEn9Se95sO8tg2FnEniOBtyFA2y4ALcZiPzpgF73U04pSsC+ZWK6qAHbC9p0M6nbuWYCE0wzkRQLgi7GUcinq5HTXLQU99tuJPT8q7gDNm2Jz+LccByODi1oco9TUDLeoqDMe6elXXX18Gl3v2bNLZvv27fIA0jPY/dE7KKV7wn6wq4ZXT0asfgvqIrjtRlKnAYBve4B24ci/ncxfU3AM4OT7AHnp+OO6+gKHlzsIID0mRMaDRgDdRwE0mcIAbieV5iBuEPCZBwEunkA+y2Z95YAiIJXdKiBh313VfvvgYNB1Jj7OfpX/7koOAPyxiA1kxXgvZRJAtwdAbip4PHwBer6CP1udPHnSfcWKFb5r1qxpxc8MDw+/+MYbbyQ3a9YMR/KiOIA//427URJAPr680lswgrswiYTgCUKp03QSHVu8eHGLlStX+qekpBCwoH///tn+/v6FAQEBBdp68NyL+i0UXwBI+wml01H8kUd9ZkAqtSSRbH+fEXVVyT3oeRx8BpVklFS6NuLWzA37Xowawb6VbGAQ3oEE0F8FICc24uPIOQBffr0+u3fvbjh27NjueXl5NzBBy5YtC7du3RoTGBiILyx3K0DUJ6R6ETPezGiOAHI2SZ72gwBaz6T9Dz30UMcNGza0sLc+6ueUKVPS+vXrd+2BBx7INh0pQoBd3QZwZh/+yGGjdxFTgcodA5DyDHEAgsYAQ1fgOOB9wP9A36KUIvfKemv1u9a/1vdk3yMoRBMB9sxkKnW1B1B1dGMztamFH46cgbQDGa+rHniISAo8+eSTHdVf7t1VO0VR/5xvAjxOzO5B6dOgOfZlIu2fN29eK0fAw/u5ZMmSdg8++GB3VBmHUF0ZGRnYRl2UqH5PoKR4DcC/j8r0JDnAndQw1hdH3js+Q+/mBB6SPpUJHp33J50Itxn0+PKbBOFmvbVr1zbhqpI5ioyM9CIpNWzYMARd+x4A8buZSnQzfWAqUCAydx1fqp8AcKtukuqiIqih/gAd5qGxHwlw+FMmRWkUL0IQ6Uoj64NQkw70I3tvdkN+IOA/AWc9Bnhcu+XqWxM3Jm3KTtnrxJEAuvWEtoebMtKfO3fOppHzt99+80IAIWN4dCVMMfvFbjuoovRpH4wS6A4uBSvjRsmmo7Jo0aKzKJUuYf8HAAxui/bRRrSPDnK1jkCkevXAYNvzIylc15d+FJ4rND5DnzE+2Q0CGxRWzmsrjUH7Zw177gYJoNuvytlMx44d81C36rZh0sOFwOCAHcQ9gFhf01FcdbMmBW+W5s+f33HdunW+H3zwwVkcCHDwaPMsml87AY58yR0joM51ldkwz8UAVK81/cg7kqc8m7ot6xaq4CnBus7+hoMU1utS4KimqxZn7JMLljKUmIkJoiNEAui2UtEV+r9Dhw42jZYXLlxgDO7qzYx/N+YJshlAFaVPQG/804nsFGRq/7/ijk+dOtUwJCSk19y5cxNV753XXQD9mwGc+BDg+iWm0hVbBlGEkwlArj7Kk0xS7Z+6reqyZ1mKwEknKX2JOS0MNwEiHglSCqY5uHKoIRKoOjoRDOpLyEqiH4MGDbpmK/OpRnkdZLjGzcEUseCAA4McEc1G0o5ly5a1MOfAqCwi22jAgAHd1fupj7Zgj9moSra00UEiAKiOogZfj72u2EANejZgz5Jc6HAZCw1SV5mEc6SQnUYexVxQ57SKa5L0qa4AYqNZWipuFpN72sPDwyZb5qeffmKRAU27cDXOMeeBfyeUPopn76+SPnqOkd69e/ei+S8UqAEIopkIAT9Q3dMIjggXy04Y8mI6171+8rp7WV6ZMgB4BHvkqafkJzHpXLLb2bnMnsIkjFjKBYlT40Koqms0dqmqSxddYFIo25aLDh8+zOyg+h1EO8gO9Y2kT32AJgNpJKcJ079a+ohEdtfIkSO7CyB6DlQ3d31V1YxwNg8gL8VjmPtnrtED5znIk0mg7ESmbpWDpBqpwpWqI2TBedrRs2fPPFsu3Lt3L5NAivFcjwHCyY5nxcKH6ilhQz/88ENTWy4kCXnixIlDBoNhL5Vvv/02huwYKhSlcGtB1P9ZUCZ3FTvPhdk8OgCqrzoQolQHgouHS6nqQCjHgelSqgRQzZZAZaoEyjtDP0aPHm0TE1a0gwKCmBRytuNZ4fkBPclfRfWQGmXLhdOmTUtWIyFUokgDcgJQOXDgQAyBisDUtWvXa46CKCwsrCuzibrjkHK/6iXUtfO4C7ulYv8cY/ZPN6P9cwlMsXcyar2GAsigGqQJsWQH0fyOrXYQGf1MLnRmALKqggnqG0ot774V67FOjz766BV16/QmNZjywv/Qxt6BZR8K0jQ6QmCKjY09QtLJESDR4IDtsIgLr7+hndeGSVlBCkVwL2Id5o2EoovMA9fG6IG7yo19tGkkgGoogPhan3xywtKOSZMmXbLlQtN8kHs7rsbZYAdx9Q1Ha/e2tOPnn3+2SX2bOHHiJVX6EFDS9mK3TwHEb8WeIIiOfQSw/w2A8x8A5BzGY7kknQhIJJHsfShbt25tQpEZFKEB0O4hJoXqCGoqWz/VCMHj2kgM4fHoxR0IBclSfasdEogkTgEavIdpR58+fWyyg/7880+mdrn747jrCba5s11Um6Jdd1L/yN6gEd9GAF1mhvl+/I+kDa2JucL+0u+LAIkRANGrAA69oQJJlUi7du06QkGm9jyYhQsXsnCiBqhq+nfWeBuZJG0aoPRICOExhe/knWcSqEzCo+YCSLCDrihq3NNPP33FFjWOvGbfffcdgsgZR+Y2PcGKO1vjfRtC+z777LMmtnSQmF+NrC5FcCfQoj6aC6EocFoLU6QOAMpSBZozScdDKHWi31clUlE6qabR0dFH7FHpyB4i76AKluYjmEfOTZhAxe0GbZRncSjPCCCvYV6sjaR4EOZqhpWXO7HirCnKfgmg6g0gHCmvpKJ6RGqHze7sbdu2sRWlHt2YGmcpqpkZ3e7eXH378ssvfW1ph5YnqFsEjKJM1XNoUo0ojIgWlTGVicCUo0qmxD0AR99GvJ2mtUyk0tkDIgr5UbfqtlO9hord42y6lzrKAFB4vpDuXVlqwBwI6awvysUIkPqq2qp49byF4sX2NaRzsNC5rgQsqGHR1jUZQMyRQIxXcIZ5ty7bcqHJne3ODW1dd3bFRXOteyEfepD0sjXubc6cOcwuu7KXSZ8SvahpAUjFql1HM/j5qEodfA8xFUXnoDoXY6s6R+olRYcjUJoDtA8CU3QCB5Cf4oGLYR647twDV5gOxjg/ZT6JgNgK8dIVoO2dKLGH4l+Uwu3uVPcBefKas3MbgXESVwFsrQCSazXvf5k6qqccxHc4evz48dnh4eE2MRi5fHF0J3d2IKpXGWBKRFKBt8E49+MzqKL0skwjR468wlbCpmD9x5j0sWhXsBwBTDXlM/fRnwD0bYh1dX7vvffO0nohW9oXos/JDvqTgYflbiBgIURP5Tes6EC4lqVKmIBOCJAuarRFndb6LZAwpmXoJXh/BecQ88cBLpxjA4Bx0R/UcHd4dc8LV66+qKupxKjEsMS4tlyocWe7m7GDmPetCS3eUxjpq6++ssl9bZKG146BKQ7MqmdLI42uqQ6HmM+QUfPInrJ14vX8+fP11C23pkzCuqp/27RXHAi7TQ4E9w7uTLKVo2Qe+E88ZzoKlBEcPOSto/PFoi4Bd0WpUw/VYJ9xKOlexmtfBOg+Hi+hNj0F6V5j8w9WdwkkeOOun6LJQYpKIHeutQsFd3YAAxC5s4v58oaKcz9+A8npQC5iW0J3yJlBTg1ybgCk7mejcok9SydYwg0GokKUkLknUMoOfPLJJ9NsmcBNSkri0eeN2XtmAPJQ7Li8A4IDYQh3ILTqqah2J6+7p3+e3iRnd453bmSu2baU5Q9BDa55hXhltXi8xRW3Zu44GFEZ1B9NuZ8BzkWDGkhaUFOlkXPNAZA\";var _2=\"iVBORw0KGgoAAAANSUhEUgAAAFAAAABBCAYAAABGmyOTAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAEeRpVFh0WE1MOmNvbS5h` J\"54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+Cjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDQuMi4yLWMwNjMgNTMuMzUyNjI0LCAyMDA4LzA3LzMwLTE4OjEyOjE4ICAgICAgICAiPgogPHJkZjpSREY`!K%cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uI`!*\"hYm91dD0iIgo`!K!`\"g%G1w`!0(bnMu`\"y#uY29tL3hhcC8xLjAv` L,ZGM9Imh0dHA6Ly9wdXJs`!n\"9kYy9lbGVtZW50cy8xLjE` O-eG1wTU0` X(ucy`%K%jb20veGFwLzEuMC9tbS8iCiAgICB4bWxuczpzdEV2dD0iaHR0cDovL25zLm`$Z\"L`&?!94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQj`!L,dGlmZj` [90aWZm`!V\"`!G-leGl`$g)`#G-2V4aWY`!R\"yIK`%_!HhtbG5zOnBob3Rvc2hvc`!~:waG90b3Nob3`\"=#` e#eG1wOkNyZWF0b3JUb29sPSJ`)X$Q` M'gQ1M0IFdpbmRvd3M`\"&\"HhtcDpDcmVhdGVEYXRlPSIyMDEwLTA1LTE5VDE1OjI0OjQ0KzAyOjAw`#B\"B4bXA6TWV0YWRhdGF` E7MwOjQ3` J29kaWZ5RGF0ZT0iMjAxMC0wNS0xOVQxNTozMDo0NyswMjowMC`\"V\"ZGM6Zm9ybWF0PSJhcHBsaWNhdGlvbi92bmQ`$#%cGhvdG9zaG9`!1'BNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkVFN0U0NjUxOUQ2MkRGMTE4QzNCQzQ4RjAwQTI3QTNB` e+Eb2N1bWVudE` j&ZG` o!E` =SPcmlnaW5hbERvY3`).\"SUQ9InhtcC5kaWQ6RUQ3RTQ2NTE5RDYyREYxMThDM0JDNDhGMDBBMjdBM0E`%9#RpZmY6T3JpZ`+g!Rpb249Ij` 2*WF`(g!sd` 7%cyMDAwMC8x` \"\"`$.\"`(j\"pZUmVzb2x1`$'!j0iNzIwMDAwLzE` #!`\"5#`(w!Ol` p(5Vbml0PSIy` 7)k5hdGl2ZURpZ2VzdD0iMjU2LDI1NywyNTgsMjU5LDI2MiwyNzQsMjc3LDI4NCw1MzAsNTMxLDI4MiwyODMsMjk2LDMwMSwzMTgsMzE5LDUyOSw1MzIsMzA2LDI3MCwyNzEsMjcyLDMwN` K!UsMzM0MzI7OTY4NTc1NDFDNzgxMzBFQUE5NTgwRUIxRDNFRUVCNjk`#N\"G`*o!6UGl4ZWxYRGltZW5zaW9uPSIxMjg`\"x$`+[!OlBpeGVsWURpbWVuc2`#N\"MTAyN`($$XhpZjpDb2xvclNwYWNlPSIx` [)`#00zY4NjQsNDA5NjAs` \"\"EsMzcxMjEs` \"\"I` 1#I` 9#MsMzc1MT` H$Qs` b\"cs` \"\"g`\"u#Q`\"}#csMzQ4NTAs` \"\"I` )#U` )#YsMzczN` C!czNzg` )#k` #!ODA` +!OD`!K!zODI` )#`!C!zODQ` )#U` )#` j\"OTYsNDE0ODMs` \"\"Q` )#` 0$c` )#g` \"\"TI` *\"T` I#TUsNDE3Mj` ;!3Mjk` \"\"zAsNDE5OD` ;!5` i#5` i#5` i#5OD` K!5O`##!E5OTE` )#`!#!5`!!#5OT`!S!5`!)#5`!r\"IwMTYsMCwyLDQsNSw2LDcsOCw5LDEwLDExLDEyLDEzLDE0LDE1LDE2LDE3LDE4LDIwLDIyLDIzLDI0LDI1LDI`'K!LDI4LDMwO0E0NjM4RjQ3Q0JBN0VEOTE0M0JCREQ0QTY4RTk3QUEz`&!#`1<(6Q29sb3JNb2`/o!` /1SUNDUHJvZmlsZT0ic1JHQiBJRUM2MTk2Ni0yLjEiP`42\"8eG1wTU06SGlzdG9yeT4`3.\"DxyZGY6U2Vx` E#` +%bGk` >\"CAgc3RFdnQ6YWN0`(j\"Jj`25#k`!Z\"`4[!zdEV2dDpp`/a7`.YK` k)3aGVu`2~F` O)zb2Z0d2FyZUFnZW50`4HDLz`#%#CA8cmRmOmxp`+k!CAgIHN0RXZ0OmFj`.l$c2F2ZWQ`,.\"` 7)luc3RhbmNl`0u'p`0z\"U`0RJ` l(ndoZW49IjIwMTAtMDUtMTlUMTU6MzA6NDcrMDI6MDA` I/NvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDUzQgV2luZG93cy`-Z\"`%O)2hhbmdlZD0iLyIv`&($PC9`&4,8L3htcE1NOkhpc3Rvcnk+Ci` B&RGVzY3Jp\";var rotY=0` #$X` $#activeTouchId` -#lastX` 9!lastY` %!scalesum=22` ?\"e` -!last=1` ,!first` d!=false` +&Rotate` &,Slide=tru` .\"gor` B!` &#Left` 3&limit1y` \"&2y` \"&3` &\"startx`!g\"tart` 0\"doLog` Y'` ;\"` ^\"` G\"` ^\"` &\"hasContent` '$Description` .!vi` \"-infoT` Z\"` &!`!3\"` &!` M\"erticalArea` ,!toolBarWidth`#\"utoO` g\"appMod`\"P\"autoDeley=auto`#@\"Delay*100`$a%ateTimer`$V%timer_is_on`#m#enableSound` +#window.onload=function initialLoad(){document.bgColor=bgd` $!;if(vrTitle==null){` '$\"\";}` 9!Sub` 2+` )%` ;%`#?'` =&` )(` C#`$k!Zoom` >$` '&0` 7&Tilt` 4)` ,!` 6'Pa` ~%` '%` U'` (3checkA`$1\"();updateOrientation();if(!`$R#`#*(ody.setAttribute(\"class\",\"` F#\");}else` /A\");}`$P#scrollTo(0,1);` T%t`#Y!`$##;setView`#3&,`\"l%,-`\"9$`!w!`$1&.length>0||`#|)` /%){set`(<#`%;$,` V&,` I)`!P'getElementById(\"info\").remove`\"<-);`)?&`*_\"`#!\"` +'`'A\"`%v-`!^'`)o*`+E#`)q)` l+` .(`,E#` A*`!*&navigator.onLine){addStats(`$k$`)\".}if(` 0\"AutoButton&&` ='){`*n(=120` f\" ` F/||` ?665`!=#` ))`'d\"!` Y,){`-%!ideauto=`$95auto_holder\");` H$.parentNode`$f#Child(` 8$);`,v\"`#_(` +#`\"k&`!M#`\"$#`!G$snd`!46sound`!A*snd`!28snd)`!)!`.\"&OnStart){`-x*setTimeout`\"P\"Rot()\",`.e%);}`!?5controls`!R%`'I6showVR();se`31\"Area`+X%Ic`+U!};`.s%`+f/`#'!c`(,\"Type=\"show_\";` )'+=get`,A*`!e5page_wrapp`!v!`+s1` p')`0_$`,\"*`!t8clearOfllineInfo();postaviPoruku();}`\"I%`!i,{if(`.>%if(getW`!<!`'\\!()<` (%Height()){return\"vert\"`&Y#` ,#hor\";}` -\"switch(`2n$`!+&){case 0:` [)break;case-9` 2%` k!` 0& 9` L%` *,18` [1default:;}}`\"Z&`%^$`%%\"trlarea`'~6toucharea\"`1P\"`,?'userAgent.match(/iPhone/i)||` )9od/i))){`!6$`(n4` 8$);var info`!N:`/~\";` A$` _4` 8$` q\"`(y$` ]:`)6-`(-!` P$`!h5` 9');`$<\";}`\"N%addEventListener`#g#`3F!\"`3V#ouch,`,u!);` 9<move\",move` *Iend\",end` (Icancel\",` \"\"` 3Dgesture`\";#onG` *\"`-q!` 5Fchange` U'C` ,!,tru` ;A`\"L!` T%End` S#`%5%`#iL` 9<`$\"3` 7<`$$1` 5<`#~7` @7`#u@` =>`#{:` >>`$!4`.{(`.,#` R.resize\",`2&-`!]?` ;=}var loadingE`*m6` ;#\");` D$`*c4` 8$`3\"7cubes`2~4\"visible\"`24(setView(`$b!Zoom`'&\"Pan`'.#ilt){scalesum=` >%*220;rotateBy`%n!(0,0,5*` M%` $$Pan`-q\"es`-R8ube`-`%esa.style.webkitPerspective=`!C$`!v*Content(vrTitle,vrSub` #$Descrip`3F\"`1]6itle\").innerHTML=` f#`#U6sub` B0`!3$;if(`!1).length>0`!,7d` E&` h+` ^';}else`4+!descTxt`#@6` d);` H#`&,4` 8#`'7#info` e#`3\"=` H$Height=` P'.offset` 3\"` C!`)K\"` C#getW` %'(`)n*verticalArea=460-` z&+5`4S!` ~$`%k\"top=` H(+\"px\"`#(#if(get`)`'()==\"hor\"` u/(300-`!]()` _X` r)` j(` >S}`'t&`#/-`%R!`#V)0;if(typeof` 2#`&2#` 9\"=\"number\"`-c$` 1#` 9.`#?&`%F%`%P$`!p#&&` \"4.clien`%@#` {+` /A`!*/body`!''body` bA` 8-;}}}return`#-)`+Z'`#^%Width`#Y)` -!`#L5` 8\"`#S-` 1\"` 8-`\"_` c!` y*` .@`#2I` h8` 7,`#K-` /#`/4(`0]!Area(){limit1y=65;`)V8` A\"x=480-toolBa`#5)` 7$32` /,if(enableAutoButton&&` ,\"Sound` r%S=` \"#+55;` $#M` ,$`!!\" ` X1!` 3W` U#`!3E` Z-+55`\"U*` 16;}` $!2x`'7\"`-C6`.fJ` o\"y=300`!>(2y`--)`!6#3x=396`&S&has`4f#==tru` d'`-:)2` k,`!B--10` y&236` %$y`\"X\"2y-58;`!+\"`3O'&&!vi` #*`\"d/vert`\"q#slideTop`!./80`#l\"2y=` >$+2` -#`!9*`(9#`()'check`(,&` %!X,` \"!Y){infoT=false;`&Y%`%\\!&&` E\">`%5$` *#Y<`(p#){playPause();`)Q#` d\"`'77` g*M` )$` n#` r0if(!firstRotate){` \"'`$t!;}togg`!!\"`!15`!,(3x` ~$` )#y`!(*2y&&useLogo`!:!`!v,`!N\"autoOn){`!3&Set();` 2\"`!S#}`'t6||!`%d*||`%c;){openIVRpage()`%%$`\"61`\"4#2y`$}#x=`\"\\\";` )!y` (\"Y` (\"`!f\"` [.{` ,#`\"$#`.=&tar`.C\"(e`$5'` -!`$8#` '!` r\"`#,1`/[%ge`0[$ById(\"auto_btn\").removeAttribute(\"class\");` 9@set` I-,\"on\")`/-'`-C#` W5sound` uU` R(`!38}`#K!x=e.targ`1|#es[0]`2V#X;` =!y` (6Y;clearOfllineInfo`.$\"timer_is_on){` \"'`*K#` P!Timeout(r`(m!TimerId)` 6\"Interval(go` 9\"`#8\"auto`);\"OnIdle){` 6P`!D(`&\\\"` L(=set` i$`$t!Rot()\",autoDeley`!E\"`,p+`#E\",`#*\")){e.preventDefaul`)[!ctive` N!Id=e.changed`#I'identifier;lastX` 01pageX` ;!Y` '5Y`'g2`*tF`)A\"`!r/`/_$`)K&mo`\".#(e`\"B1if(`\"M)){for(var i=0;i<`!t,.length;i++`-?\"`\"4,i`\"}(==` n+var t`\"g.i]`&r!`\"x\"`.F$-10){`%7\"By`!~\"`#s!,`#Y!,` H\"X,` O#)`$.#` 0#`#|#` 6#;}break;}}`\"p'en`!:\"`\"c3var lastInfo`$p8` <(`$x8`#O!nfo`*f#=`*h5info\"`$5!`.b!&&`/r*`#?\"razX=Math.abs` C\"x-`!f%`!x\"razY=`/S\"` 2%`&W!razX<50&&razY<0&&`0a,if(appMode`!(\"slideTop=380`/~#` *)getWindowHeight()-80;}`\"C'.style.top=` M$+\"px\";`%%#` ,&20;`!@*`,.#`4,#=`%U$58;`0n!Slide` =#`*p(updateIcon()\",300)`2a&`\"S)>0`3?/`!e2verticalArea`!q*` -)`!q.`)s!`!^@`!j(`!f&` `*&&` M&){prikaziPoruku(\"` 1! d` D& DOWN to hide it\")`!*(`+K\"`! $`\"X+` ZKUP to show` p3`3]!`1^*`+H#>0){`,V\" `\"b\"`)\\'cancel`)a%`.z*0;` ?&`*q6curX,curY`'H\"e`)\"6cubes`)7\"!e`!L$;}rotY-=(curX`(e!X)*0.2;rotX+` 2!Y` 2!Y` 1\"if(useLimits`(g!rotY<=left` 0!||rotY>=righ` ''X<=Bottom` ('>=Top` +!`#p-PANO ` 6!\")`!\\\"`*j\"max(`!\"%,` -\"in(`!#&,rotY))`!y!` I&`!0'` K&`!5$,rotX)`!!\"` I'-90` B&90` >$e`(L#webkitTransform=\"translateZ(\"+scalesum+\"px)`$V#X(\"+`#P!\"deg` -$Y` /\"Y` /\"\"`%''onGestureStart(e`#h!timer_is_on){` \"'`({#clear`*~$` {\"TimerId)` 6\"Interval(go` 9\");}if(autoR` +!OnIdle){` 6P`!D(`(0!` K)=`,U(`!*#()\",autoDeley`!E\"check`'a!Area`'^()`1u1if(enableAutoButt`/\\#!autoOn){togg` 8\"Set();` 2\"`)n$`/j\"` e/`(6$`#~/C`2`!`3?7esa`)(:holder`)E\"`%c$>149&&` &$<301){` &$=(1-(1-e.` ,!)/20)*` 4$` X(<150||` i%300`(i-ZOOM`(p&` x%`'e!round(`'y%15`'w'300,` F$)));esa`'})Perspe`,[!=`!R%`#*0End`#6!` @!last=`\"0#;`#;/` V&stubOu`(#!` +9playPause(`-J\"myAudio`#|0sByTagName(\"audio\")[0]`$]!playBtn`$L6sound_btn`$_\"` #.paused||` ($stopped){` j#.removeAttribute(\"class\");` 9$set` --,\"off\"`3-#` *]n\");}doS`%(!`#/(` +%`\"bS`\"D@` 8%lay();`3h,ound ON`\"C%` c)` 84PAUSED\")`&C(`*L&(){`,o,`-g#`-2#On`,YR`,[%`!e#`->Q`, 9`!{/` B!`$;!auto`&f9auto`&x&first`.3!`-Z!`\"Q$` ++`#Q+A`#0%`$.#`!.#`&B6` 9$`'&= `!>#Btn!=null`!;-if(!` +!`!<\"`!A8`%8&`(<\"`!l6FF`%c!`!H\\`(_!}`0<$`,{&penIVRpage(`!|!navigator.onLine&&!appMode&&linkLogo`$i\"r=confirm(urlC` %\"`$T!r=`%J!){window.location=\"http://\"+` b$URL+\"/\";`20\" if(useOfflineInfo){showOfl` )$(`(G)`3v!A`!Y\"`!y\"`!,#`!|&standalone){`\"\"#`'&#`#t!` +$`(z\"`\"n.`(\"!`!3){`'%6aa\").innerHTML=\"\"`0\"(`!x,`#?!nowWidth=getW`!v!` *!`4/#nowHeight` 5&` *\"` 9#winw` Y!` _$+2` 0$h` R\"` Y%` 3#imgX`3.(` Q$/2)-104` <$Y` 5+` ^\"` @!20;`\"7F<div `3o!='top:0px;left` $!`!v!:\"+`!~$+\"px;`!r\"` 0\"` &\"` 2!backg`!J!-color: rgba(0,0,0,0.7);'><img`!!(\"+imgY` Z!`!/!` +!X` +!'  src='../vr_files/styling/o`&X\".png'></div>`$\\(`)c#Icon(topPos,leftPos){`%x\"\"`!7.` C\"`!?(` M#`!-=logo-ipho`!J$`!@(update`!F!`'x!use`)Y\"if(getOrient`)6!()==\"hor\"`&Q\"`!7#=limit3x+13`%5!`!a\"` /#y+8`$p6bbb`$})`\"[7`-s&!hasDescription||` \"*&&!vi` %(`!U3`'D\"`!]+15`!\"g`*)6` [,\"\";}`,%'addStats`*7#currentTime=new Date`!x!month=` 4'.getMonth()+1` >!date` 2,Date`*T#year` /,FullYear` <#minutes` v-` 1\"` >#hour` 2-Hours();`!a\"`!h!+\"\";`!N!date+\"\";` v$` #+\"\";` f\"` m!+\"\";if(` V!.length==1){` l\"\"0\"+` %!;}if(date` 8(`!\"!\"0\"+date` =!` }#` \\)`!8#` f!` &\"` F!`!9!` =(`!O\"\"0\"+` %!;}var javi=\"vr5\"`\"^#stUrl=`1a+.host+` %,pathnam`$c\"sta` U!unescape(\"%68%74%74%70%3A%2F%2F%77%77%77%2E%76%72%68%61%62%69%74%61%74%2E%63%6F%6D` Q!3` 1&73` W!0` {!0%3` n\"3%3D\")+encodeURIComponent(`\"-#)+\"&d=`#h#+\"-`#P\"` $!year+\"&t=`\"t#` 0!`$f%&s=\"+javi+\"&dev=1`#%\"el=`(4%create`(9#(\"iframe\");el.setAttribute(\"id\",\"statifrm\")`)P6ccc\").appendChild(el` j\"tyle.visibility=\"hidden\"` {.src\",`$1#);`.m\"`-i'autoRot(){timer_is_on=true;clearInterval(gorotate);if(enableAutoButton){togg` ,\"Set();autoOn=false;}` U$=set` i%\"play`!7!\",10`!I/` 7%{if(`!T'`+H\"k`#p&`#'-ubes\");scalesum`4S(` ,$*100)/100;rotX` 6(rotX` 1)Y` /+Y` 4&`0#imits`!b!rotY<=left` 0!+2){goLeft`\"c$`/v$rotY>=righ` D\"-` @&`#y!}}if(!` ,\"){rotY+=0.05`.l#rotY-` *#` h\"X>0.1` E!X-=0.1` ~)X<-` 5%+` 4&` +!=0` ^!`\"q$>221){` &$-=` ^'` -$<219` 9&+` ;$` )%=220;}k`' #webkitTransform=\"translateZ(\"+` ]%\"px) `%a\"X(\"+`!e!\"deg` -$Y` /\"Y` /\"`)8#sa`%(:holder\");esa`!B)Perspective=`!;$`\"l$`&a#`&^'`2|\"Poruku(Tekst`%(!showNotifi`-G\"s`&t\"`!99ddd`!H#`3-&` m!`!X'opac`*1!0.8\";se`1E!out(\"sakrij`!B#)\",1200)`!R5Duze`!g$` W~`!L)30`!T!`!O%` 2*`!\"H`!*,\"`*v(ostav`$1$` NEvar por`*I)getW`26!Width()/2)-76` C$`*V)` B%Height` F\"36`!c'left=porX+\"px\"` .'top=porY` 2\"`3x!cacheStatusValues=[];` $-[0]=\"un` 3!d\"` -/1]=\"idle` (02]=\"checking` ,03]=\"download` ,34]=\"updateready` /05]=\"obsolete`)Y\"` ?!=w`#'!.appl`(A#Cache` \\\".addEventListener(\"`\"=#,log` 5!,`-u!)` 66`\"2$` )E`\"@(` ,Eerror` %Fno`#)\"` (F`#3%` )Eprogress` (F`$W(` D-`(n%` 1$(e`(m\"online,s`%)!,type,message;` 5\"=navigator.onLine?\"yes\":\"no\";` Q\"=`%_.`!_\"` 9\"];type=e.type;` w#=\"` y\": \"+` $\"` 2$+=\", event: \"+` H(` 5!` n\": \"+` $\";if(` {!=`$`#&&`!b,){` W& (prolly a syntax ` Q! in manifest)\";stopLog()`3:!consoleLog){` %#.log(` o#` ?\"`\"d#`)c#){` Y&if(informWhenOfflineAvailable&&`!v$`(5#||` )#`&=%)&&!appMode){`/s.\"Panorama is a` p$ o`!#\". <br/>Add Bookmark` ,\"(+ sign)` 6%to Home Screen\");}}}`*)3`&><`&F$(){` J4swap` %!();`#H(\"swap`+X\" has been called\");}`'H$doLog=setInterval(`!)'`&W\"`!L\"();},10`1n!if(!`%J.`%!'`2)&` ,${clear` |%`!2!`0\"`,}@remove`,wI` =2`-(;` @1`-'?` C1`-09` =1`-0<` @1`-3<` @1`-6<` @1`-<9`'Z%`'A-`*7#\",stacemo`-z-` 1#`.\"$provera=e.data;if(` *$=\"opaopa\"` C\"skidaj=document.getElementById(\"cubes\");` B\".parentNod`\"7$Child(` 8\");alert(\"Licence for this domain is missing. Please visit vrhabitat.com\");`\"a#lo`'A\"=unescape(\"%68%74%74%70%3A%2F%2F%77%77%77%2E%76%72%68%61%62%69%74%61%74%2E%63%6F%6D%2F%0A%09%09%09\"`(b\"metas`\"Y0sByTagName(\"head\")[0];` J!`\"\\4` 8!);}}"))